// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockErp.Api.Infrastructure.Persistence;

#nullable disable

namespace MockErp.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MockErpDbContext))]
    [Migration("20260729130258_InitialMockErpSchema")]
    partial class InitialMockErpSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpAccountingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDateUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ErpCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ErpOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErpVoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExternalOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("VoucherType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id")
                        .HasName("PK_ErpAccountingEntries");

                    b.HasIndex("ErpOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpAccountingEntries_ErpOrderId");

                    b.HasIndex("ErpVoucherNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpAccountingEntries_ErpVoucherNumber");

                    b.HasIndex("ExternalOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpAccountingEntries_ExternalOrderId");

                    b.HasIndex("ErpCustomerId", "EntryDateUtc")
                        .HasDatabaseName("IX_ErpAccountingEntries_ErpCustomerId_EntryDateUtc");

                    b.ToTable("ErpAccountingEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpAccountingEntries_Amounts_NonNegative", "[TotalDebit] >= 0 AND [TotalCredit] >= 0");

                            t.HasCheckConstraint("CK_ErpAccountingEntries_Balanced", "[TotalDebit] = [TotalCredit]");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpAccountingEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("AccountingEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("CreditAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DebitAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ErpCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SequenceNumber")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_ErpAccountingEntryLines");

                    b.HasIndex("AccountCode", "CreatedAtUtc")
                        .HasDatabaseName("IX_ErpAccountingEntryLines_AccountCode_CreatedAtUtc");

                    b.HasIndex("AccountingEntryId", "AccountCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpAccountingEntryLines_Entry_Account");

                    b.HasIndex("AccountingEntryId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpAccountingEntryLines_Entry_Sequence");

                    b.HasIndex("ErpCustomerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ErpAccountingEntryLines_ErpCustomerId_CreatedAtUtc")
                        .HasFilter("[ErpCustomerId] IS NOT NULL");

                    b.ToTable("ErpAccountingEntryLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpAccountingEntryLines_AccountCode_V1", "[AccountCode] IN ('120','600','391')");

                            t.HasCheckConstraint("CK_ErpAccountingEntryLines_Amounts_NonNegative", "[DebitAmount] >= 0 AND [CreditAmount] >= 0");

                            t.HasCheckConstraint("CK_ErpAccountingEntryLines_OneSided", "([DebitAmount] > 0 AND [CreditAmount] = 0) OR ([DebitAmount] = 0 AND [CreditAmount] > 0)");

                            t.HasCheckConstraint("CK_ErpAccountingEntryLines_Sequence_Range", "[SequenceNumber] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ErpCustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExternalCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_ErpCustomers");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ErpCustomers_Email");

                    b.HasIndex("ErpCustomerCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpCustomers_ErpCustomerCode");

                    b.HasIndex("ExternalCustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpCustomers_ExternalCustomerId");

                    b.ToTable("ErpCustomers", (string)null);
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpIdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastAccessedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ResponseStatusCode")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK_ErpIdempotencyRecords");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpIdempotencyRecords_IdempotencyKey");

                    b.HasIndex("OperationType", "CreatedAtUtc")
                        .HasDatabaseName("IX_ErpIdempotencyRecords_OperationType_CreatedAtUtc");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("IX_ErpIdempotencyRecords_ResourceType_ResourceId");

                    b.ToTable("ErpIdempotencyRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpIdempotencyRecords_ResponseBody_IsJson", "ISJSON([ResponseBody]) = 1");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<Guid>("ErpCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErpOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ExternalOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MarketOrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("OrderPlacedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK_ErpOrders");

                    b.HasIndex("ErpOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpOrders_ErpOrderNumber");

                    b.HasIndex("ExternalOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpOrders_ExternalOrderId");

                    b.HasIndex("MarketOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpOrders_MarketOrderNumber");

                    b.HasIndex("ErpCustomerId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ErpOrders_ErpCustomerId_CreatedAtUtc");

                    b.ToTable("ErpOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpOrders_GrandTotal", "[GrandTotal] = [Subtotal] + [VatTotal]");

                            t.HasCheckConstraint("CK_ErpOrders_Totals_NonNegative", "[Subtotal] >= 0 AND [VatTotal] >= 0 AND [GrandTotal] >= 0");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrderAddress", b =>
                {
                    b.Property<Guid>("ErpOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("TR")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ErpOrderId")
                        .HasName("PK_ErpOrderAddresses");

                    b.ToTable("ErpOrderAddresses", (string)null);
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ErpOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExternalProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetLineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id")
                        .HasName("PK_ErpOrderLines");

                    b.HasIndex("ExternalProductId")
                        .HasDatabaseName("IX_ErpOrderLines_ExternalProductId");

                    b.HasIndex("ErpOrderId", "ExternalProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpOrderLines_ErpOrderId_ExternalProductId");

                    b.ToTable("ErpOrderLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpOrderLines_Amounts_NonNegative", "[UnitPrice] >= 0 AND [NetLineAmount] >= 0 AND [VatAmount] >= 0 AND [LineTotal] >= 0");

                            t.HasCheckConstraint("CK_ErpOrderLines_LineTotal", "[LineTotal] = [NetLineAmount] + [VatAmount]");

                            t.HasCheckConstraint("CK_ErpOrderLines_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_ErpOrderLines_VatRate_Range", "[VatRate] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExternalProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetContent")
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("UnitType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_ErpStocks");

                    b.HasIndex("ExternalProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpStocks_ExternalProductId");

                    b.HasIndex("Quantity")
                        .HasDatabaseName("IX_ErpStocks_Quantity");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpStocks_Sku");

                    b.ToTable("ErpStocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpStocks_NetContent_Positive", "[NetContent] > 0");

                            t.HasCheckConstraint("CK_ErpStocks_Quantity_NonNegative", "[Quantity] >= 0");

                            t.HasCheckConstraint("CK_ErpStocks_ReorderLevel_NonNegative", "[ReorderLevel] >= 0");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ErpOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExternalOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExternalProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK_ErpStockMovements");

                    b.HasIndex("ErpOrderId")
                        .HasDatabaseName("IX_ErpStockMovements_ErpOrderId");

                    b.HasIndex("ExternalOrderId", "ExternalProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpStockMovements_ExternalOrderId_ExternalProductId");

                    b.HasIndex("ExternalProductId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ErpStockMovements_ExternalProductId_CreatedAtUtc");

                    b.ToTable("ErpStockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_ErpStockMovements_Balance", "[PreviousQuantity] + [QuantityChange] = [NewQuantity]");

                            t.HasCheckConstraint("CK_ErpStockMovements_Quantities_NonNegative", "[PreviousQuantity] >= 0 AND [NewQuantity] >= 0");

                            t.HasCheckConstraint("CK_ErpStockMovements_QuantityChange_NotZero", "[QuantityChange] <> 0");
                        });
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpAccountingEntry", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpCustomer", "ErpCustomer")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("ErpCustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MockErp.Api.Domain.Entities.ErpOrder", "ErpOrder")
                        .WithOne("AccountingEntry")
                        .HasForeignKey("MockErp.Api.Domain.Entities.ErpAccountingEntry", "ErpOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ErpCustomer");

                    b.Navigation("ErpOrder");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpAccountingEntryLine", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpAccountingEntry", "AccountingEntry")
                        .WithMany("Lines")
                        .HasForeignKey("AccountingEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MockErp.Api.Domain.Entities.ErpCustomer", "ErpCustomer")
                        .WithMany("AccountingEntryLines")
                        .HasForeignKey("ErpCustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccountingEntry");

                    b.Navigation("ErpCustomer");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrder", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpCustomer", "ErpCustomer")
                        .WithMany("Orders")
                        .HasForeignKey("ErpCustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ErpCustomer");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrderAddress", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpOrder", "ErpOrder")
                        .WithOne("Address")
                        .HasForeignKey("MockErp.Api.Domain.Entities.ErpOrderAddress", "ErpOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ErpOrder");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrderLine", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpOrder", "ErpOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ErpOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ErpOrder");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpStockMovement", b =>
                {
                    b.HasOne("MockErp.Api.Domain.Entities.ErpOrder", "ErpOrder")
                        .WithMany("StockMovements")
                        .HasForeignKey("ErpOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ErpOrder");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpAccountingEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpCustomer", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("AccountingEntryLines");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MockErp.Api.Domain.Entities.ErpOrder", b =>
                {
                    b.Navigation("AccountingEntry");

                    b.Navigation("Address");

                    b.Navigation("Lines");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
