// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recommendation.Api.Infrastructure.Persistence;

#nullable disable

namespace Recommendation.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecommendationDbContext))]
    partial class RecommendationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.CustomerPreferenceScore", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PreferenceType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FrequencyScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime>("LastPurchasedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<decimal>("RecencyScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("CustomerId", "PreferenceType", "ReferenceId")
                        .HasName("PK_CustomerPreferenceScores");

                    b.HasIndex("CustomerId", "PreferenceType", "Score")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_CustomerPreferenceScores_CustomerId_PreferenceType_Score");

                    b.ToTable("CustomerPreferenceScores", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerPreferenceScores_Counts_NonNegative", "[PurchaseCount] >= 0 AND [TotalQuantity] >= 0");

                            t.HasCheckConstraint("CK_CustomerPreferenceScores_FrequencyScore_Range", "[FrequencyScore] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CustomerPreferenceScores_RecencyScore_Range", "[RecencyScore] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CustomerPreferenceScores_Score_Range", "[Score] BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.OrderSnapshot", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DistinctProductCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK_OrderSnapshots");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderSnapshots_CorrelationId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_OrderSnapshots_OccurredAtUtc");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderSnapshots_OrderNumber");

                    b.HasIndex("CustomerId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_OrderSnapshots_CustomerId_OccurredAtUtc");

                    b.ToTable("OrderSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderSnapshots_DistinctProductCount_Positive", "[DistinctProductCount] > 0");

                            t.HasCheckConstraint("CK_OrderSnapshots_TotalQuantity_Positive", "[TotalQuantity] > 0");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.OrderSnapshotItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("PK_OrderSnapshotItems");

                    b.HasIndex("ProductId", "OrderId")
                        .HasDatabaseName("IX_OrderSnapshotItems_ProductId_OrderId");

                    b.ToTable("OrderSnapshotItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderSnapshotItems_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("EventId")
                        .HasName("PK_ProcessedEvents");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ProcessedEvents_CorrelationId");

                    b.HasIndex("EventType", "ProcessedAtUtc")
                        .HasDatabaseName("IX_ProcessedEvents_EventType_ProcessedAtUtc");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductAffinity", b =>
                {
                    b.Property<Guid>("SourceProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CoOccurrenceCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("Lift")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("RecommendedOrderCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SourceOrderCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Support")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TotalOrderCount")
                        .HasColumnType("int");

                    b.HasKey("SourceProductId", "RecommendedProductId")
                        .HasName("PK_ProductAffinities");

                    b.HasIndex("SourceProductId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ProductAffinities_SourceProductId_Score");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceProductId", "Score"), new[] { "RecommendedProductId", "Confidence", "Lift" });

                    b.ToTable("ProductAffinities", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductAffinities_Confidence_Range", "[Confidence] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_ProductAffinities_Counts_NonNegative", "[CoOccurrenceCount] >= 0 AND [SourceOrderCount] >= 0 AND [RecommendedOrderCount] >= 0 AND [TotalOrderCount] >= 0");

                            t.HasCheckConstraint("CK_ProductAffinities_DifferentProducts", "[SourceProductId] <> [RecommendedProductId]");

                            t.HasCheckConstraint("CK_ProductAffinities_Lift_Positive", "[Lift] > 0");

                            t.HasCheckConstraint("CK_ProductAffinities_Support_Range", "[Support] BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductPopularity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("ProductId")
                        .HasName("PK_ProductPopularity");

                    b.HasIndex("Score")
                        .IsDescending()
                        .HasDatabaseName("IX_ProductPopularity_Score");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Score"), new[] { "ProductId", "SoldQuantity", "OrderCount" });

                    b.ToTable("ProductPopularity", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductPopularity_Counts_NonNegative", "[SoldQuantity] >= 0 AND [OrderCount] >= 0");

                            t.HasCheckConstraint("CK_ProductPopularity_Score_Range", "[Score] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_ProductPopularity_Window", "[WindowStartUtc] < [WindowEndUtc]");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductSimilarity", b =>
                {
                    b.Property<Guid>("SourceProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("BrandScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("CategoryScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("PriceScore")
                        .HasColumnType("decimal(12,6)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("SourceProductId", "RecommendedProductId")
                        .HasName("PK_ProductSimilarities");

                    b.HasIndex("SourceProductId", "SimilarityScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ProductSimilarities_SourceProductId_SimilarityScore");

                    b.ToTable("ProductSimilarities", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductSimilarities_AmountScore_Range", "[AmountScore] BETWEEN 0 AND 0.10");

                            t.HasCheckConstraint("CK_ProductSimilarities_BrandScore", "[BrandScore] IN (0, 0.10)");

                            t.HasCheckConstraint("CK_ProductSimilarities_CategoryScore", "[CategoryScore] IN (0, 0.20, 0.65)");

                            t.HasCheckConstraint("CK_ProductSimilarities_DifferentProducts", "[SourceProductId] <> [RecommendedProductId]");

                            t.HasCheckConstraint("CK_ProductSimilarities_PriceScore_Range", "[PriceScore] BETWEEN 0 AND 0.15");

                            t.HasCheckConstraint("CK_ProductSimilarities_Total_EqualsComponents", "[SimilarityScore] = [CategoryScore] + [BrandScore] + [PriceScore] + [AmountScore]");

                            t.HasCheckConstraint("CK_ProductSimilarities_Total_Range", "[SimilarityScore] BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductSnapshot", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NetContent")
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("UnitType")
                        .HasColumnType("tinyint");

                    b.HasKey("ProductId")
                        .HasName("PK_ProductSnapshots");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductSnapshots_Sku");

                    b.HasIndex("BrandId", "IsActive", "IsInStock")
                        .HasDatabaseName("IX_ProductSnapshots_BrandId_IsActive_IsInStock");

                    b.HasIndex("CategoryId", "IsActive", "IsInStock")
                        .HasDatabaseName("IX_ProductSnapshots_CategoryId_IsActive_IsInStock");

                    b.ToTable("ProductSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductSnapshots_NetContent_Positive", "[NetContent] > 0");

                            t.HasCheckConstraint("CK_ProductSnapshots_Price_NonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.RecommendationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("InputRecordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OutputRecordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("RunType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RecommendationRuns");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_RecommendationRuns_CorrelationId");

                    b.HasIndex("RunType", "StartedAtUtc")
                        .HasDatabaseName("IX_RecommendationRuns_RunType_StartedAtUtc");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("IX_RecommendationRuns_Status_StartedAtUtc");

                    b.ToTable("RecommendationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationRuns_CompletedAfterStarted", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_RecommendationRuns_Counts_NonNegative", "[InputRecordCount] >= 0 AND [OutputRecordCount] >= 0");

                            t.HasCheckConstraint("CK_RecommendationRuns_ParametersJson_IsJson", "ISJSON([ParametersJson]) = 1");
                        });
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.OrderSnapshotItem", b =>
                {
                    b.HasOne("Recommendation.Api.Domain.Entities.OrderSnapshot", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderSnapshotItems_OrderSnapshots_OrderId");

                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "Product")
                        .WithMany("OrderSnapshotItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OrderSnapshotItems_ProductSnapshots_ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductAffinity", b =>
                {
                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "RecommendedProduct")
                        .WithMany("RecommendedAffinities")
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAffinities_ProductSnapshots_RecommendedProductId");

                    b.HasOne("Recommendation.Api.Domain.Entities.RecommendationRun", "Run")
                        .WithMany("ProductAffinities")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAffinities_RecommendationRuns_RunId");

                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "SourceProduct")
                        .WithMany("SourceAffinities")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAffinities_ProductSnapshots_SourceProductId");

                    b.Navigation("RecommendedProduct");

                    b.Navigation("Run");

                    b.Navigation("SourceProduct");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductPopularity", b =>
                {
                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "Product")
                        .WithOne("Popularity")
                        .HasForeignKey("Recommendation.Api.Domain.Entities.ProductPopularity", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductPopularity_ProductSnapshots_ProductId");

                    b.HasOne("Recommendation.Api.Domain.Entities.RecommendationRun", "Run")
                        .WithMany("ProductPopularity")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductPopularity_RecommendationRuns_RunId");

                    b.Navigation("Product");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductSimilarity", b =>
                {
                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "RecommendedProduct")
                        .WithMany("RecommendedSimilarities")
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSimilarities_ProductSnapshots_RecommendedProductId");

                    b.HasOne("Recommendation.Api.Domain.Entities.RecommendationRun", "Run")
                        .WithMany("ProductSimilarities")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSimilarities_RecommendationRuns_RunId");

                    b.HasOne("Recommendation.Api.Domain.Entities.ProductSnapshot", "SourceProduct")
                        .WithMany("SourceSimilarities")
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSimilarities_ProductSnapshots_SourceProductId");

                    b.Navigation("RecommendedProduct");

                    b.Navigation("Run");

                    b.Navigation("SourceProduct");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.OrderSnapshot", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.ProductSnapshot", b =>
                {
                    b.Navigation("OrderSnapshotItems");

                    b.Navigation("Popularity");

                    b.Navigation("RecommendedAffinities");

                    b.Navigation("RecommendedSimilarities");

                    b.Navigation("SourceAffinities");

                    b.Navigation("SourceSimilarities");
                });

            modelBuilder.Entity("Recommendation.Api.Domain.Entities.RecommendationRun", b =>
                {
                    b.Navigation("ProductAffinities");

                    b.Navigation("ProductPopularity");

                    b.Navigation("ProductSimilarities");
                });
#pragma warning restore 612, 618
        }
    }
}
