// <auto-generated />
using System;
using ErpIntegration.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpIntegration.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    partial class IntegrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.ErpCustomerLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErpCustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ErpCustomerLinks");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpCustomerLinks_CustomerId");

                    b.HasIndex("ErpCustomerCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ErpCustomerLinks_ErpCustomerCode");

                    b.ToTable("ErpCustomerLinks", (string)null);
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("RequestPayloadMasked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayloadMasked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ResultType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_IntegrationAttempts");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_IntegrationAttempts_CorrelationId");

                    b.HasIndex("StepId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationAttempts_StepId_AttemptNumber");

                    b.HasIndex("StepId", "StartedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_IntegrationAttempts_StepId_StartedAtUtc");

                    b.ToTable("IntegrationAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationAttempts_AttemptNumber_Positive", "[AttemptNumber] > 0");

                            t.HasCheckConstraint("CK_IntegrationAttempts_Duration_NonNegative", "[DurationMs] IS NULL OR [DurationMs] >= 0");

                            t.HasCheckConstraint("CK_IntegrationAttempts_RequestPayloadMasked_IsJson", "[RequestPayloadMasked] IS NULL OR ISJSON([RequestPayloadMasked]) = 1");

                            t.HasCheckConstraint("CK_IntegrationAttempts_ResponsePayloadMasked_IsJson", "[ResponsePayloadMasked] IS NULL OR ISJSON([ResponsePayloadMasked]) = 1");
                        });
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte?>("CurrentStepType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("MarketOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_IntegrationBatches");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationBatches_CorrelationId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationBatches_EventId");

                    b.HasIndex("MarketOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationBatches_MarketOrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationBatches_OrderNumber");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_IntegrationBatches_CustomerId_CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_IntegrationBatches_Status_CreatedAtUtc");

                    b.ToTable("IntegrationBatches", (string)null);
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetLineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id")
                        .HasName("PK_IntegrationOrderLines");

                    b.HasIndex("BatchId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationOrderLines_BatchId_ProductId");

                    b.ToTable("IntegrationOrderLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationOrderLines_Amounts_NonNegative", "[UnitPrice] >= 0 AND [NetLineAmount] >= 0 AND [VatAmount] >= 0 AND [LineTotal] >= 0");

                            t.HasCheckConstraint("CK_IntegrationOrderLines_LineTotal", "[LineTotal] = [NetLineAmount] + [VatAmount]");

                            t.HasCheckConstraint("CK_IntegrationOrderLines_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_IntegrationOrderLines_VatRate_Range", "[VatRate] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationOrderSnapshot", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderPlacedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BatchId")
                        .HasName("PK_IntegrationOrderSnapshots");

                    b.ToTable("IntegrationOrderSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationOrderSnapshots_GrandTotal", "[GrandTotal] = [Subtotal] + [VatTotal]");

                            t.HasCheckConstraint("CK_IntegrationOrderSnapshots_Totals_NonNegative", "[Subtotal] >= 0 AND [VatTotal] >= 0 AND [GrandTotal] >= 0");
                        });
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte?>("LastErrorType")
                        .HasColumnType("tinyint");

                    b.Property<short?>("LastHttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("SequenceNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("StepType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_IntegrationSteps");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationSteps_IdempotencyKey");

                    b.HasIndex("BatchId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationSteps_BatchId_SequenceNumber");

                    b.HasIndex("BatchId", "StepType")
                        .IsUnique()
                        .HasDatabaseName("UX_IntegrationSteps_BatchId_StepType");

                    b.HasIndex("Status", "NextAttemptAtUtc", "SequenceNumber")
                        .HasDatabaseName("IX_IntegrationSteps_Status_NextAttemptAtUtc_SequenceNumber");

                    b.ToTable("IntegrationSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationSteps_Attempts_Range", "[AttemptCount] >= 0 AND [MaxAttempts] > 0 AND [AttemptCount] <= [MaxAttempts]");

                            t.HasCheckConstraint("CK_IntegrationSteps_Sequence_Range", "[SequenceNumber] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("EventId")
                        .HasName("PK_ProcessedEvents");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ProcessedEvents_CorrelationId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationAttempt", b =>
                {
                    b.HasOne("ErpIntegration.Api.Domain.Entities.IntegrationStep", "Step")
                        .WithMany("Attempts")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_IntegrationAttempts_IntegrationSteps_StepId");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationBatch", b =>
                {
                    b.HasOne("ErpIntegration.Api.Domain.Entities.ProcessedEvent", "ProcessedEvent")
                        .WithOne("Batch")
                        .HasForeignKey("ErpIntegration.Api.Domain.Entities.IntegrationBatch", "EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_IntegrationBatches_ProcessedEvents_EventId");

                    b.Navigation("ProcessedEvent");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationOrderLine", b =>
                {
                    b.HasOne("ErpIntegration.Api.Domain.Entities.IntegrationBatch", "Batch")
                        .WithMany("OrderLines")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_IntegrationOrderLines_IntegrationBatches_BatchId");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationOrderSnapshot", b =>
                {
                    b.HasOne("ErpIntegration.Api.Domain.Entities.IntegrationBatch", "Batch")
                        .WithOne("OrderSnapshot")
                        .HasForeignKey("ErpIntegration.Api.Domain.Entities.IntegrationOrderSnapshot", "BatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_IntegrationOrderSnapshots_IntegrationBatches_BatchId");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationStep", b =>
                {
                    b.HasOne("ErpIntegration.Api.Domain.Entities.IntegrationBatch", "Batch")
                        .WithMany("Steps")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_IntegrationSteps_IntegrationBatches_BatchId");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationBatch", b =>
                {
                    b.Navigation("OrderLines");

                    b.Navigation("OrderSnapshot");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.IntegrationStep", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ErpIntegration.Api.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Navigation("Batch");
                });
#pragma warning restore 612, 618
        }
    }
}
